#!/bin/tcsh -f

if (! -d armv7) mkdir armv7
if (! -d lib) mkdir lib

rm armv7/*

make clean

./configure --enable-cross-compile --arch=arm --disable-doc --disable-ffmpeg --disable-ffplay --disable-ffserver --target-os=darwin --cc=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc --as='gas-preprocessor.pl /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc' --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk --extra-cflags='-arch armv7 -I/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk/usr/include' --extra-ldflags='-arch armv7 -L/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk/usr/lib/system' --enable-shared --prefix=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk/usr --cpu=cortex-a8 --enable-pic --disable-asm

make

mv libavcodec/libavcodec.a armv7/
mv libavcodec/*.dylib armv7/
mv libavdevice/libavdevice.a armv7/
mv libavdevice/*.dylib armv7/
mv libavformat/libavformat.a armv7/
mv libavformat/*.dylib armv7/
mv libavutil/libavutil.a armv7/
mv libavutil/*.dylib armv7/
mv libswscale/libswscale.a armv7/
mv libswscale/*.dylib armv7/

rm lib/*.a

cp armv7/*.a lib/
