#!/bin/tcsh -f

if (! -d armv6) mkdir armv6
if (! -d lib) mkdir lib

rm armv6/*

make clean

./configure --enable-cross-compile --arch=arm --disable-doc --disable-ffmpeg --disable-ffplay --disable-ffserver --target-os=darwin --cc=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc --as='gas-preprocessor.pl /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc' --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk --extra-cflags='-arch armv6 -I/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk/usr/include' --extra-ldflags='-arch armv6 -L/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk/usr/lib/system' --enable-shared --prefix=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS5.0.sdk/usr --cpu=arm1176jzf-s --enable-pic --disable-asm

make

mv libavcodec/libavcodec.a armv6/
mv libavcodec/*.dylib armv6/
mv libavdevice/libavdevice.a armv6/
mv libavdevice/*.dylib armv6/
mv libavformat/libavformat.a armv6/
mv libavformat/*.dylib armv6/
mv libavutil/libavutil.a armv6/
mv libavutil/*.dylib armv6/
mv libswscale/libswscale.a armv6/
mv libswscale/*.dylib armv6/

rm lib/*.a

cp armv6/*.a lib/
